name: Semantic version increment, libraries building and publishing to NPM

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch origin tags for Lerna (see https://bit.ly/2KNS172)
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Auth with repo for push
      run: git remote add -f pub https://${GITHUB_TOKEN}@github.com/koshevy/codegena.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - name: Install yarn
      run: npm install yarn -g
    - name: Install dependencies with yarn
      run: yarn install --frozen-lockfile
    - name: Clear already built libs
      run: yarn run clear:prebuilt-libs
    - name: Set git credentials
      run: git config --global user.email "koshevy@gmail.com" && git config --global user.name "Alexander Koshevy"
    - name: Run publishing script (powered by LernaVersion and AngularCLI)
      run: ./build-and-publish.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
